### ISSUE TITLE
Email verify is broken

### ISSUE THREAD

**Issue by eric48906** [aithedev/TikTok-Account-Generator#13]
The others just don't work and

- https://lasagna.pro/: The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by aithedev** [comment]
people either spammed or their working on the site..

**Comment by aithedev** [comment]
You can open a pull request if you'd like

**Comment by ExoticCitron** [comment]
why are you talking to yourself..
