### ISSUE TITLE
How to fix: "Maximum number of attempts reached. Try again later."

### ISSUE THREAD

**Issue by underjk** [aithedev/TikTok-Account-Generator#14]
Response: {'data': {'captcha': '', 'desc_url': '', 'description': 'Maximum number of attempts reached. Try again later.', 'error_code': 7}, 'message': 'error'}
How to fixed, sir?

**Comment by aithedev** [comment]
Looks like an issue caused by the device generator.

**Comment by underjk** [comment]
fixed how much?

**Comment by underjk** [comment]
> Looks like an issue caused by the device generator.

fixed how much?
