### ISSUE TITLE
Captcha issue?

### ISSUE THREAD

**Issue by VersaceXcodes** [aithedev/TikTok-Account-Generator#25]
`{'data': {'captcha': '', 'desc_url': '', 'description': 'Maximum number of attempts reached. Try again later.', 'error_code': 7}, 'message': 'error'}`

when verifying new account, is there a captcha solver? how to bypass? thanks

**Comment by All3xJ** [comment]
I have the same bug

**Comment by rossSec** [comment]
The problem is the proxies, try and use different proxies. I stumbled upon this and removing the usage of proxies proved this was the reason.

**Comment by aithedev** [comment]
Device gen issue
