### ISSUE TITLE
Direction of the code.

### ISSUE THREAD

**Issue by jodiekurnia** [aithedev/TikTok-Account-Generator#28]
Hi bro, love your work. however, I fix email generator by using account_generator_helper library to get random mail.
I run your code in a 10k loop, with iprotation each time it run, and only run one account per ip, yet from 10k run I still get 0 account, all return the same err..
can we fix it? I see some hardcoded, "OPPO" and "en" in your request params, does changing that to the correct device from Device class help?
really looking for your response here...
Thanks..
```
{'data': {'captcha': '', 'desc_url': '', 'description': 'Maximum number of attempts reached. Try again later.', 'error_code': 7}, 'message': 'error'}
```

**Comment by winterrx** [comment]
Any fix to this? I am still getting this error @hireza @jodiekurnia

**Comment by aithedev** [comment]
patched
