### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ArdianTheDev** [aithedev/TikTok-Account-Generator#31]
{'data': {'captcha': '', 'desc_url': '', 'description': 'Maximum number of attempts reached. Try again later.', 'error_code': 7}, 'message': 'error'}

**Comment by winterrx** [comment]
Same error here. @ArdianTheDev @aithedev

**Comment by aithedev** [comment]
ya its patched

**Comment by jodiekurnia** [comment]
> ya its patched

So it's no longer working? Tiktok has patched this method?

**Comment by aithedev** [comment]
tiktok has patched the creation of accounts on older versions
now you need to use xargus and xladon which i have but im not going to post anything for free anymore

**Comment by jodiekurnia** [comment]
> tiktok has patched the creation of accounts on older versions
> now you need to use xargus and xladon which i have but im not going to post anything for free anymore

Understood, care to gave me your whatsapp number so we can discuss pricing?

**Comment by aithedev** [comment]
t.me/aithedev is my telegram

**Comment by hacknapier** [comment]
TikTok Captcha Solving Service is available here with demo to Login successfully into your TikTok Account.
https://rapidapi.com/flyCaptcha/api/flycaptcha
