### ISSUE TITLE
How about X-Ladon & X-Argus?

### ISSUE THREAD

**Issue by dvwzj** [aithedev/TikTok-Account-Generator#6]
I known this is not about your project but
Did you know about how to generate x-ladon & x-argus?

I think some endpoints is required these headers
Thank,

PS. Sorry for my english

**Comment by aithedev** [comment]
x-argus and x-ladon aren't required in versions under 20 but yes, i'm able to generate them

**Comment by dvwzj** [comment]
Thanks for your response

How did you known?
I'm try to use many tool like IDA, Jadx but I got no luck

However, for ladon I just found something to explore with but I just don't know where to find some param (random bytes)
