### ISSUE TITLE
[Enhancement] Proxy Error Handler

### ISSUE THREAD

**Issue by Sysys242** [aithedev/TikTok-Account-Generator#8]
Ayo, that a really good tools but there is some things you can upgrade:

- Idk if issue but sometimes i got 0 as device id/ other shit so output is that: 0:0:email:password:a065a670efd8c21cd2823272dbc71d83
- Fix too many attempt with reseting session & changing proxy for every account ( maybe tried to fix but idk )
- Check if thread > number of acc to generate

Idk if i am goinna to do this, maybe yes or nah, if i do it, i will open a pull requests :)

**Comment by aithedev** [comment]
1. proxy issue or something it happens once in a moon
2. device gen issue 
3. yeah there could be some error handlers but no point if youre not retarded
